// frontend/angular/src/app/presentation/create/create.component.ts
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ICreateFood } from '@core/dist/useCases/foods/UseCreateFood';
import { useCreateFood } from '@core/dist/useCases/foods/';
import { Router } from '@angular/router';

@Component({
  selector: 'app-create',
  standalone: true,
  imports: [FormsModule],
  templateUrl: './create.component.html',
  styleUrl: './create.component.css',
})
export class CreateComponent {
  defaultValues: ICreateFood = {
    name: '',
    category: '',
    price: 0,
  };
  defaultErrors = {
    name: '',
    category: '',
    price: '',
  };
  formValues = this.defaultValues;
  formErrors = this.defaultErrors;

  constructor(private _route: Router) {}

  async handleSubmit() {
    const data = await useCreateFood.execute(this.formValues, () => {
      this._navigateToList();
      this._resetForm();
    });
    this._setFormError(data);
  }

  private _navigateToList() {
    this._route.navigate(['/']);
  }

  private _setFormError(data: any) {
    this.formErrors = data;
  }

  private _resetForm() {
    this.formValues = this.defaultValues;
    this.formErrors = this.defaultErrors;
  }
}

<section class="flex items-center justify-center flex-col h-screen">
  <form (submit)="handleSubmit()" class="w-96">
    <div class="w-full max-w-sm min-w-[200px] mb-4">
      <label htmlFor="name">
        Name:
        <input
          data-id="food-create-input-name"
          id="name"
          class="w-full bg-transparent placeholder:text-slate-400 text-slate-700 text-sm border border-slate-200 rounded-md px-3 py-2 transition duration-300 ease focus:outline-none focus:border-blue-500 hover:border-blue-300 shadow-sm focus:shadow"
          type="text"
          placeholder="name"
          [(ngModel)]="formValues.name"
          [ngModelOptions]="{ standalone: true }"
        />
        <span
          data-id="food-create-error-input-name"
          class="text-sm text-red-600"
          >{{ formErrors.name }}</span
        >
      </label>
    </div>

    <div class="w-full max-w-sm min-w-[200px] mb-4">
      <label htmlFor="price">
        Price:
        <input
          data-id="food-create-input-price"
          id="price"
          class="w-full bg-transparent placeholder:text-slate-400 text-slate-700 text-sm border border-slate-200 rounded-md px-3 py-2 transition duration-300 ease focus:outline-none focus:border-blue-500 hover:border-blue-300 shadow-sm focus:shadow"
          type="number"
          placeholder="price"
          [(ngModel)]="formValues.price"
          [ngModelOptions]="{ standalone: true }"
        />
        <span
          data-id="food-create-error-input-price"
          class="text-sm text-red-600"
          >{{ formErrors.price }}</span
        >
      </label>
    </div>

    <div class="w-full max-w-sm min-w-[200px] mb-4">
      <label htmlFor="category">
        Category:
        <input
          data-id="food-create-input-category"
          id="category"
          class="w-full bg-transparent placeholder:text-slate-400 text-slate-700 text-sm border border-slate-200 rounded-md px-3 py-2 transition duration-300 ease focus:outline-none focus:border-blue-500 hover:border-blue-300 shadow-sm focus:shadow"
          type="text"
          placeholder="category"
          [(ngModel)]="formValues.category"
          [ngModelOptions]="{ standalone: true }"
        />
        <span
          data-id="food-create-error-input-category"
          class="text-sm text-red-600"
          >{{ formErrors.category }}</span
        >
      </label>
    </div>

    <button
      data-id="food-create-btn-create"
      class="rounded-md bg-blue-700 text-white p-2 mt-2 w-full"
      type="submit"
    >
      Cadastrar
    </button>
  </form>
</section>

// frontend/nextjs/src/pages/create/index.tsx
import createPresentation from "@/presentation/foods/create"

const createFoodView = () => {
  const { handleChange, handleSubmit, formErrors } = createPresentation()
  return (
    <section className="flex items-center justify-center flex-col h-screen">
      <form onSubmit={handleSubmit} className="w-96">
        <div className="w-full max-w-sm min-w-[200px] mb-4">
          <label htmlFor="name">
            Name:
            <input
              data-id="food-create-input-name"
              id="name"
              className="w-full bg-transparent placeholder:text-slate-400 text-slate-700 text-sm border border-slate-200 rounded-md px-3 py-2 transition duration-300 ease focus:outline-none focus:border-blue-500 hover:border-blue-300 shadow-sm focus:shadow"
              type="text"
              placeholder="name"
              onChange={handleChange}
            />
            <span
              data-id="food-create-error-input-name"
              className="text-sm text-red-600"
            >
              {formErrors?.name}
            </span>
          </label>
        </div>

        <div className="w-full max-w-sm min-w-[200px] mb-4">
          <label htmlFor="price">
            Price:
            <input
              data-id="food-create-input-price"
              id="price"
              className="w-full bg-transparent placeholder:text-slate-400 text-slate-700 text-sm border border-slate-200 rounded-md px-3 py-2 transition duration-300 ease focus:outline-none focus:border-blue-500 hover:border-blue-300 shadow-sm focus:shadow"
              type="number"
              placeholder="price"
              onChange={handleChange}
            />
            <span
              data-id="food-create-error-input-price"
              className="text-sm text-red-600"
            >
              {formErrors?.price}
            </span>
          </label>
        </div>

        <div className="w-full max-w-sm min-w-[200px] mb-4">
          <label htmlFor="category">
            Category:
            <input
              data-id="food-create-input-category"
              id="category"
              className="w-full bg-transparent placeholder:text-slate-400 text-slate-700 text-sm border border-slate-200 rounded-md px-3 py-2 transition duration-300 ease focus:outline-none focus:border-blue-500 hover:border-blue-300 shadow-sm focus:shadow"
              type="text"
              placeholder="category"
              onChange={handleChange}
            />
            <span
              data-id="food-create-error-input-category"
              className="text-sm text-red-600"
            >
              {formErrors?.category}
            </span>
          </label>
        </div>

        <button
          data-id="food-create-btn-create"
          className="rounded-md bg-blue-700 text-white p-2 mt-2 w-full"
          type="submit"
        >
          Cadastrar
        </button>
      </form>
    </section>
  )
}

export default createFoodView
